image: node:14.15.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@14.2.8
    - npm install
    - ng build
  artifacts:
    paths:
      - public
  only:
    - main
