image: node:14.15.0
pages:
  cache:
    paths:
      - node_modules/
  script:
  - npm install

install_ang:
  stage: install_angular
  image: node:14
  script:
  - npm install -D typescript @angular/cli @angular/compiler
  - npm link @angular/cli

build_ang:
  stage: build
  image: node:14
  script:
  - npm run build
