image: node:lts
pages:
  stage: deploy
  script:
  - npm install -g @angular/cli@14.2.0
  - npm install
  - ng build
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - main
